language: elixir
elixir:
  - 1.6.0
otp_release:
  - 20.0
services:
  - postgresql
addons:
  - postgresql: "9.6"
before_script:
  - cp apps/ecom/config/travis.exs apps/ecom/config/test.exs
  - mix do ecto.create, ecto.migrate
env:
  - MIX_ENV=test REPLACE_OS_VARS=true
