language: elixir
elixir:
  - 1.6.0
otp_release:
  - 20.0
services:
  - postgresql
before_script:
  - cp config/travis.exs config/test.exs
  - mix do ecto.setup
env:
  - MIX_ENV=test REPLACE_OS_VARS=true
